#!/usr/bin/env bash
set -x
set -e
export APP=${1:?"app is required"}
export VERSION=${2:?"version is required"}
export BUILD_DIR=./build/linux
export RELEASE_APP_NAME=scale-dev-linux

rm -f "$BUILD_DIR/$APP"
mkdir -p "$BUILD_DIR"

env GOOS=linux GOARCH=amd64 go build -ldflags="-X github.com/scaleci/scale/cmd.version=${VERSION}" -x -v -o $BUILD_DIR/$RELEASE_APP_NAME github.com/scaleci/scale

echo "Binary built successfully: $BUILD_DIR/$RELEASE_APP_NAME"
