title = "Rails App"

[global]
  # If build_with is not spcified then "Dockerfile" is assumed
  build_with = "Dockerfile.test"
  version = 1
  test_results_path = "/tmp/test-results/rspec.xml"
  [global.env]
    RAILS_ENV = "test"
    AUTH_URL = "http://example.com/a/auth"
    AUTH_CLIENT_ID = "deadbeef"

[services]
  [services.database]
    image = "scaleci/postgres:9.6"
    ports = ["5432/tcp"]

  [services.redis]
    image = "scaleci/redis:2.1"
    ports = ["6379/tcp"]

[stages]
  [stages."db.setup"]
    command = "bundle exec rake db:create db:structure:load"
    # parallelism is 1 by default (so only one container is spawned)

  [stages.rspec]
    command = """
bundle exec rspec --profile 10 \
          --format RspecJunitFormatter \
          --out /tmp/test-results/rspec.xml \
          --require ./lib/block_progress_formatter.rb \
          --format BlockProgressFormatter \
          $(scale tests glob "spec/**/*_spec.rb" |xargs scale tests split)
"""
    depends_on = ["db.setup"]
    parallelism = 8

  [stages.rubocop]
    command = "bundle exec rubocop"
    depends_on = ["db.setup"]
    # parallelism is 1 by default (so only one container is spawned)
